### ISSUE TITLE
ii communication with ER-301 is lost (until reboot) if a message is sent while the pull-ups are set to false

### ISSUE THREAD

**Issue by nordseele** [monome/crow#279] opened 2019-12-23 17:04 UTC
Here's a possible issue with the firmware 1.02 discovered as I was experimenting with the ER-301 via I2c from Max (Max -> Crow -(ii)> Er-301. | ER-301 is the only device on the bus, directly connected to Crow

If a message ( i.e: `ii.er301.tr_pulse(1)` )  is sent to the ER-301 while the pull-up resistors are turned off, it's impossible to re-establish the connection/ send another message to the 301 after having turned the pull-up resistors on again. A reboot or `^^reset` is required.
(please see screenshot)

I think that the pull-up resistors are "on" by default when Crow starts, so in theory there's no particular reason to turn them off and on again but it might be interesting to know this issue can happen (unless the issue is related to my setup).

1 -> ✅
2 -> ✅
3 -> ❌
 
<img width="907" alt="Capture d’écran 2019-12-23 à 17 24 05" src="https://user-images.githubusercontent.com/47527859/71369615-994fca80-25ab-11ea-9b0e-15de4ea2e446.png">

Can you reproduce this issue ? 

[details="here's a patcher"]
<pre><code>
----------begin_max5_patcher----------
4824.3oc6c01aiibj9yd9Uv039PNbdE5WX2M4g6BtraRlC3lMWvtygEGlDXP
I0VlioH0QR4wdCR9se8KjTjT7klVMkrSl4CdHaxVrpmtppqtphM+Ku6pqWl7
DO6Zm+UmO4b0U+k2c0UpljMbUw4Wc81fmVEEjotsqWkrcKON+5azWKm+Ttp8
uOINluJ2IOw46SS9hy29qKuk38aCii34p9CKZLbspWIK+72R.k2YV9yQbU60
5ax97xNCJZcWP9p6Ci2bap3IpIdj6BvMNtH4egH5BxMNHvBfyeV1i+56dm7O
2bhrHdPN5tj37rveQQ+P5BvwLpK0BLJAn3TDCH+Or9DWKyonSkSI1XHE5O+b
J7T4TWqI7ZGFcKOKKXC+HFMLbwt8QQ628qtKHJi+OeiinEdJF.Wjmdq3RY7e
ET2Zw8kmtuuaqSPC0EnAq.MIkrJIJIUyyfE99T.y6lNOBJ49NP6JAS4CINXq
Fv+MogAQlNN.GU2BCzCDTO0HQcZQ+6j+7NttGWec0kVtoA2IPLeJ7lNOp9uX
Q2PSseaRCVGJknqwRK2bWXTj5261RZ7ZMU0wcn9Kb5zaqegJJGcSs+LXWJ6A
3lZ+oudDDuQOdp0ON9F1klrKIMOLIVolIL82wOx97j5Hl3WZt0sd8pEAmWsn
B61EZQHJ4qZQeUKZRZQuFm4ALu5L0m3A549UUlupxTSkIl+EgP3QZLYNR2ZC
hWmcadxsqDK6p7VZJtKkrckbqGh4RTHLjP8n3lL+3t.C6zEX3oqZLpywXe8X
Eplpg8.xcNKEJW7zE+Rzh+u8787KANhY8iiNeWRzZKXmA6ijKMloWmbwLz0o
86CWulGW+WY.KOpG.Os.uK.bA4GFwejmlUnXT7Cc00A61Uq4qp0E4nzm0.M6
lplBi0MgqZJk+XXY+oUsFjJXybAOtOUCKOQKWUl7mIYMOMdenhTzMJjWdW4O
XIxvztofYp3HnWJFQfVUPiTuNJY0C700DXEvyNdbX7tTdlPCOnxXP4kWyuKX
eT9sMF9QK5752Erh2am6TuRZMNbcRrjHZ.0xlKebexAp3M4eOvLp6HNXWGcV
HLJfkdtXlfI2msLHUNRrrv.Y4EySRhZdop9EwuKu3x6Biiagh4I65+hogate
f9tLQbwsC8aqtR1s6i0W8Vg4f7ayBdrIZmGDEUXen4O+SAwgaCx44g5g.Dn5
h73.Aidelv1aTTC9UekG63JqEBwq3eIbc98EyHb3JhaObWoPz0UixqC2vyxa
1VdvlrlsbjcAQS6WVnjdaNe6tHAWz7FZD+u5Zj0sj1n8ACrRSyp42GD+fyyI
6c9wj0hQwju4a9l52XWFJaaUDUuCGyg8NUReV.U529Z8As4upvDdU47IE1Hl
ADov22LYXRqMeswnAwxnAzWO6pmd9.xYGPD3vmuapn.11n.QIPPPXE+6c1Qg
njjcN42mlrey8NJGPb1GmGF4HzYyetdWhBi4qR1qclDMQbyGXYfCiUpPtD1B
HvC5QjBQTkDE9LBe6y3EnlPbJKOIk6Hrk6DFK5jffcJ055EHwSDH87lIfDfW
3CXPJsRazkcFAx07nfmqfKmkO6f2lYMwOO57fZXp6BFfBcEnlu+YW5aURrvs
VUluxdd6xjH4QOv46bpYseCOW5or0D.csLThTqH.KTjKQRHv+rK+EdmSPIpI
Waq.5BicxRRh4oNRuIDWFB1J.z64h1+RnfOb1HcpoOf0cp.qs82.4pmaULeB
B.AHl3Xc.Ro1dFlFKts0zrNKchl5zrrIKjgLZdVrbQ7.BThEZMXT80Y04hNW
FDu45aTK977fX+RjS8HAzaPGOBzf1FzzqE0ERW3VL0.gZFncVArWjHF0alPK
JZAsvijWshX4I54KlLnwlJnAMBzvLoMJs0eslpAhXmKvR6ZBdppiTnkwpB64
0wJW1DDvNW30+hCbpXkK01XUQ.FwPgxHFvvhi8UklynXUnb56ylkqHmkSUIz
kLOSN5iK8MvTK7mUwJoyVNnWfrk08knrnYXK7.hIFE9RPbeENs3+lCdwTAKH
bdTDESGJ7g.AHtuRUDC21bMRF4vkkErJwJruxgcnuzXuYBV2EkDjaeoKEDzK
r.5IVO1VFpz4crNS0k+cT2Cpc4xk90NRnMi.XX7Z9S0xViUvPMkMUi791d0f
EVsHPuAPw5vzzPmCo2QtH3dhquhrjWuaXKKYe5pxwuRqQNMov07r7v3prc8o
C9O3zlUpxeJTmvcRUR9KS8tQixSknky23.MfnkKxsehFrPmu2azj+LSul.xR
QxgnWvMkH87RuDSEJNdf3hQuFIOLJ41YkinM+ktVmMbvkmG.mJO.mGdfNE4l
oaLo1suMb8tDg6KYkyqq83gRDyqiIdxh1PLYVillIgOpoVPYvSXjqM+RXRlS
lRAO.kxjkSEyuYSyE+xrD+dlL9JiBkQzK0hiOkCF9dGhTEj0SSx.yWFtghA1
CMMmnBzBSIclFEMUnCBMvxx7OiDyTiBcHcdQfW2KgRB0qTVmBHTDrg3uto4j
eMQ7mxdUL93ara5DK3AYQikUR20xpoZ8s5JG61f77zvk6y0q.odoANoJbZST
xxfnh5Wpp92FpbmNTSTu6.8ZmRDM0YipDQmgRsEbFdkObm0xWunrRgPltNhf
FTWosJa8dKh69R4fsp7WYkale1p2Wq7tHLyu9N.kSwvhR6YlGJ+6vRIF5qKl
BcgjQc0.oGXVpkXvv0RLbvZI9C7GxEOjYnXhQesXh+GlhINRIEcqbL1d0U7.
oIPnfHDjV6jyihtscUzdRUnFjZ8flqMeBNjZOYnee8jScGzjSNEw1ImBQpUN
1XCAoyZVOCuy4eJD57qEtMqp7LcohLQYKWaKaApiaPf2qLoqVuKUSP6rOIOr
0S4dM.z0T7y5426kkapomjXfQ1pHDCSM0rmytWTdOgfYwDNjLkzdVXb5RAbM
eCqapU9mjT6t84ex8Ou3wjn7Lm+cGve55oNKfmkQYWeE.W7VdBuHyTZJrkEw
+xKC07mGTidImAvHTCeRBa11qLr6aDgM7oHrwlGT60uvF5jD1rtaZuUrrgNE
gMx7fZu9E1fmjvF11SH7FQVCdJxZnYAzrhn17T.V.Cyryw4gscMA3JCsKQEd
RR0wcW+GrYIKUFyKXy3EJ6.uPY8wKzKKu3NEdAAFgYburLCYJBYELS+RYjKK
yPmxHCdLwLzkkYXSYjAOl9O9xxLdSR+eLcFvkkY7mjg4wzYlmJySFcMip2A3
nlyHpxpCxTSkp2LyZdBVuAb.ULp5rYpnHfXSKJHCsD.8TEjRsSlKJ2zxsANp
A4RbVOD.YccldDAgm+QDSKbX33d.favI52nkVmUvWyOaQe4UeVmBZHW3AJWc
xLQ4HqMdnmQQtriCZHxSlIBGaaBGUW0FMep1t1SC.bdobh0o7ykvB0ZTN9LK
svrNketvbO6ofdlky8sNkaFleNppxNqNngpJn9J2nKS4YJ.fCD2neaIp1RMC
2DmjxWEEt5g52po0ImrIUpqquQ655CTU4V6CpWxacUuCLsOIfRg4ps6+xxoS
7nd3EUIhCUkDVeKm8tzjsm2McVaT7j3Ycyps3UPGV7JDe7GPfQKURaVwxy2t
C74njkOGUrrqND45c+p2FErbpXxE0dG4spCEOMm+icI61uqZSY3Mhh37pIJr
EWqLlgT5kTUb2JAKlVsS+71X.BQmUMvh8S.8VQMAM8gG6pt02Wk.UMKeg9nC
fHmiQ.2h3AeBeyALUDt82b.S6ms+lCXN890u4.szGdy4vGxByyfG5ySfNV15
MALWfEsicyQ6Ic1xEhtqe92Fimv4cZohUmAAEehDvy0DSp6qYYBnGSaGrhhQ
1iC4b8XOzWVzaD8n5N01o3jwOZWCd1HbeO6hVZEpD2BHWOeDhnVdr5rdD9Ml
ZoSmZaGtRuBpA1f1fmLs05wZPsPb797flXzuzYTb0I1fxPiQYCSZ5s3.nWQ5
y0ZVdL6PavQnM1fjFUSL95AzhgWeKLfd5BaEuz6k6vcjCmchzVKqAljITiUa
0a71E.ou+ISqygEFDBTlkSU.3fGeFjwp0Xqyrt1uIiGtSjGKRPcAWUrt2lmA
J1O6.UmcpCV.SXjhIrNMa4nI7j5SJPumRnK6O8V.j5jSEDPmKP.QLQ4fdzSR
6xQq2cZ4Co06Lcq2W5ieWo6+8jt86HsJUFZ+wZ4lyAO21uNL4mTuIv29C738
ZW1JegkaBE0VlS6jfz4Z.a4SKx2EBUNYhgXFhpNRb.gTuzWtt4hEcIkw22kJ
8DVcjGBSvpEy0paGVgnubyoR+0ry2C31y20NAV1wZ9DxBsVnG1u59au7tFIS
4lBIoTwUa6F70aE.ZXYepK40bvXa3Sm5fPEA1MlhYTWl9S8mmKFp.G2V3xKD
NaMfa4AAah0eX+pfgv4l6hLLBDqj8P9XOe8QDHf52bUGY7HgZofhazaFRbiJ
AeHkgzBtd..rIl2XEUByH+2hkI57SAwYN+Dea3R4mftpasZob2FJ+7Wjwqfb
rOBR0jWohChIGka9rBVsR.aMynlrG5DoQ.ZxUpb51hEEb311ck4QoLEn3Afd
d5iD+Jn9COyDkceYBhUR7dU1N7X.hmm9nifk1h8zRffJ+GSej9WZVLhzS78.
tPlZjQH44xXZzE4qQbBsbVlSTg3Gb+fXE209VG1sdQ8LX+oZKCndPG9jJU0M
SC6QYvsQH4jxq1hOBxysECXIB5IwBHb9Q9l8QAEyMdZ+Z+9jTmOD9HeH1raP
eH6CBga4DyXKw1eLUX6R2aisyNrnNysgAvOuW340cgqp46Uuil0Jm2iiCloF
MaYf9G2uL7ACrI2arm6vHrojRWVgMIF2mWyt83ng3TxKwSCg.J6bYzcX5.aK
iU+7G+8Fqb.kdMqs46ADxIJUhR+maIlVSz2qeI3+ymWmlrgG+QkTvvlqQJaC
JmXPPBU6ofbtTEc3OjPMAHjCTxkTBFpTpgheDjAdV3RgPf1oeeD0UMfP7gds
CQ8kSD2Hult3KOoagbHEKTPUiGLWpuewQ.+F4f+DEwCV7vfST0sOyll.jlyl
2qj9uIdcPD24GRhSFSPenm7HB5F5BcqQgw7xzJiBp7REtx7U73KswbSmG0uw
F+9s07ddL+wfSY5RCbibjYWMkodgA53vxMv95roINv2EVbDifmgEY6U4wvwG
cJKxtaY0w3LaJq9c0J1zQkXK1zT8pvPPwQVmr9sUo57UDQ89fv3+lwJ23J+G
N9H6SZ5uTjCQbGopBq1Gbatu8ZYZB8phn9uxhBWW9I3wLYqVTyfQgxTiec5F
lwFNGw1rMwqOvWOM8vtlknKtkNqj8ODjmF9zp7znSf5sJAwy4oCZ7vhhDmUS
O+gj0ke2oMvpngyjNfKOuHbxpL7jLgL2Jn+g8aWNLwzkkpimzbFHs+X3p7ww
pK934er19i8qHuM9oUI63l6twgL24ik+qyPTc4.4OFrz5KKpKImQsuXUlRr7
pkS1A5t8mniURMuFN9XxF4ZUrl6rCLnzaHJsLK8+rcjjqeFcz7mCdjeWR51+
l0Q3o64IXgsBk55fzG91X4FL92phTvPL2Qo.vvDD1SLHbqzmYUAsuJ78dJNc
HkIeBpXszDgvHnv18KKrDeM0+iKoDl9n4YjxEBYJFgVwRvNpQ5AR+Y6PQJqU
ZcZVm2fgMRvJMK41u4xYuwcadCs9njgUjj+bwK.N..u1Z+Tnwxdd8E+P5ULe
YDW38gtBV9tjjGFKt6GjGO5fCRiqh3AolFycfECoqYOl+Av34m2EF+fwlOoR
akdUFjvE4VYbeFLniGMItA8oOQuaZ7W3fRbGxCq5AfqezHtMa.E1Y.oFuamX
sYN9S3L5IweOXY9AczE9YYg5doc6OR5T73KFrSIuJ2XIUV6JG4GJJe.e2hpj
z2G6wJNh4Y00uqeC69tn87x8q.CijurBjYEY99.G5WmurIAll7k3ISgih7Vj
B+9mClNABP9DcAYvXXLRWqVHnv5n8Iv2mx4u.JTgdUgbBRkp91m39Q95ISZr
JalvJ+I.HLAMCJH+u7nnjuLLIdb4xQ7A.uglKyCQz0xCyC5o+LPSDRDjYiAP
uEY.UHveuXwdSWDoJV.DeDjnKSm5SWZEBb29zcCGpsdWaJqpb3bU0Gix.fTE
iLxbCt.juNFI.puRI.4QnHOaxWo7U7vGGN6OcIST4RvAdBX8hwIU6bv6GoTq
aNefKkpCXlvHKqnzXERq93AQ6yiTTFOdc1qMqyY4KOrtXaUK6CELGqP04keG
+5mjq87+PPdhyGj92YumeVN+t8QQ4SKH7lFnr1kfnGg.0QLkhYXcoOSEpbVM
oHkL0LwSVzyYjXoH5JMDWoZfQ9XeqZcLWtwD9Z5cj3Kx0I87zKSTfb.RsPCb
0VXAqHb58GdVLseM5eaXZ9yN+tMIFDcVCCgZ2Ac.56CndESv3VjwVJ.neUL7
eI.qnO+028+S9qK12
-----------end_max5_patcher-----------
</code></pre>

[/details]

**Comment by trentgill** [comment] 2020-08-02 19:59
Closing as it has not been reported since 2.0 & noone with the devices has tested and confirmed it's still broken.

**Closed by trentgill** 2020-08-02 19:59 UTC
